import type { ModuleManifest } from '@boilerbear/core';

export const sanity: ModuleManifest = {
  id: 'sanity',
  name: 'Sanity',
  category: 'misc',
  tags: ['cms', 'headless', 'content'],
  description: 'Headless CMS with real-time collaboration and GROQ query language.',
  homepage: 'https://www.sanity.io',
  license: 'MIT',
  popularity: 1_300_000,
  versions: { range: '^3.65.0', min: '3.65.0' },
  languages: ['js'],
  packages: {
    deps: [
      { name: '@sanity/client', version: '^6.22.0' },
      { name: '@sanity/image-url', version: '^1.1.0' },
    ],
    devDeps: [],
  },
  requires: [],
  conflicts: [],
  recommends: [],
  appliesTo: [
    'react',
    'next',
    'vue',
    'nuxt',
    'svelte',
    'sveltekit',
    'solid',
    'solid-start',
    'astro',
    'remix',
    'preact',
    'lit',
    'alpine',
    'htmx',
    'ember',
    'mithril',
    'stencil',
    'marko',
  ],
  setup: [
    {
      kind: 'envVar',
      key: 'SANITY_PROJECT_ID',
      example: 'abc123',
      required: true,
    },
    {
      kind: 'envVar',
      key: 'SANITY_DATASET',
      example: 'production',
      required: true,
    },
  ],
  maintainers: ['sanity-io'],
  docs: { quickstart: 'https://www.sanity.io/docs/getting-started' },
};
